#!/bin/bash

#Password Generator Script

read -p "Enter the password length: " PASS_LENGTH
for VAR in $(seq 1 1); #how many times password will generate, you can set range
do
    openssl rand -base64 48 | cut -c1-$PASS_LENGTH
    #-base64(Encode) 48 is length 
    #cut is for user input column -c1 is column1
done
